# Generated by Django 3.0.7 on 2020-07-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20, null=True, unique=True)),
                ('dni', models.CharField(max_length=20, null=True, unique=True)),
                ('matricula', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mes', models.CharField(max_length=15)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('division', models.CharField(max_length=5, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuotaEstablecida', models.DecimalField(decimal_places=2, max_digits=8)),
                ('montoPagar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fechaPago', models.DateField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPago', models.DateField(auto_now=True)),
                ('total', models.CharField(max_length=20, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Alumno')),
                ('cuotaEstablecida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Cuota')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Curso'),
        ),
    ]
