# Generated by Django 3.0.7 on 2020-08-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_auto_20200819_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
