# Generated by Django 3.0.7 on 2020-09-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_alumno_oculto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuota',
            old_name='mes',
            new_name='numeromes',
        ),
    ]
