# Generated by Django 3.0.7 on 2020-09-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_auto_20200902_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='numeromes',
            field=models.CharField(max_length=2),
        ),
    ]
