# Generated by Django 3.0.7 on 2020-09-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0007_auto_20200911_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='division',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
