# Generated by Django 3.0.7 on 2020-10-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0008_auto_20200917_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='cuota',
            name='numeromes',
            field=models.IntegerField(),
        ),
    ]
