# Generated by Django 3.0.7 on 2020-10-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0009_auto_20200930_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
