# Generated by Django 3.0.7 on 2020-10-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0010_cuota_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esquema_Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('numeromes', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='alumno',
        ),
        migrations.AddField(
            model_name='cuota',
            name='fechaPago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Recibo',
        ),
    ]
